phases:
  install:
    commands:
      - echo "Java version:"
      - java -version
      - echo "Gradle permission"
      - chmod +x ./gradlew
  build:
    commands:
      - echo "Building APK..."
      - ./gradlew assembleDebug
