version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Using Java 17"
      - chmod +x ./gradlew
  build:
    commands:
      - echo "Building APK..."
      - ./gradlew assembleDebug

artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
