version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Gradle...
      - chmod +x ./gradlew
  build:
    commands:
      - echo Building the APK...
      - ./gradlew assembleDebug

artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
  discard-paths: yes
